name: pokedex
description: "Pokédex app — Flutter course."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.5
  http: ^1.2.2
  dio: ^5.7.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.11.0
  image_picker: ^1.2.2

dev_dependencies: 
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.15.0
  freezed: ^3.2.5
  json_serializable: ^6.13.2

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/MyApp/
    
  fonts:
    - family: Lato
      fonts:
        - asset: fonts/Lato-Regular.ttf
        - asset: fonts/Lato-Bold.ttf
          weight: 700

    - family: PokemonGb
      fonts:
        - asset: fonts/PokemonGb-RAeo.ttf

    - family: CoC
      fonts:
        - asset: fonts/Clash_Regular.otf
        - asset: fonts/Clash_Bold.otf
          weight: 700

